[language.typescript]
filetypes = ["typescript"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]

[language.csharp]
filetypes = ["csharp"]
roots = ["*.sln"]
command = "omnisharp-server"
args = ["-v"]
