[language.typescript]
filetypes = ["typescript"]
roots = ["package.json"]
command = "typescript-language-server"
args = ["--stdio"]

[language.csharp]
filetypes = ["csharp", "cs"]
roots = ["*.sln", "*.csproj"]
command = "/home/saxonj/.cache/nvim/nvim_lsp/omnisharp/run"
args = ["--languageserver"]
