(defun adf-parser--children (children)
  "Parse all children"
  (cl-mapcar 'adf-parser-to-org children))

(defun adf-parser--apply-mark (text mark)
  "Apply mark to the text."
  (let-alist mark
    (cond ((string= .type "backgroundColor")
           text)
          ((string= .type "code")
           (format "~%s~" text))
          ((string= .type "em")
           (format "/%s/" text))
          ((string= .type "link")
           (format "[[%s][%s]]" .attrs.href text))
          ((string= .type "strike")
           (format "+%s+" text))
          ((string= .type "strong")
           (format "*%s*" text))
          ((string= .type "subsup")
           (format "%s{%s}" (if (string= "sub" .attrs.type) "_" "^") text))
          ((string= .type "textColor")
           text)
          ((string= .type "underline")
           (format "_%s_" text)))))

(defun adf-parser--apply-many-marks (text marks)
  "Apply the list of marks in order"
  (cl-reduce 'adf-parser--apply-mark marks :initial-value text))

(defun adf-parser-to-org (node)
  "Parses an ADF tree to org-mode style text."
  (let-alist node
    (cond ((string= .type "blockquote")
           (format "#+begin_quote\n%s\n#+end_quote\n"
                   (string-join (adf-parser--children .content) "\n")))
          ((string= .type "bulletList")
           (string-join (adf-parser--children .content) "\n"))
          ((string= .type "codeBlock")
           (format
            "#+begin_src %s\n%s\n"
            .attrs.language
            (string-join (adf-parser--children .content) "")))
          ((string= .type "date")
           (format-time-string
            "%a %e %b %Y %R\n"
            (string-to-number .attr.timestamp)))
          ((string= .type "doc")
           (string-join (adf-parser--children .content) "\n"))
          ((string= .type "emoji")
           "")
          ((string= .type "expand")
           (string-join (adf-parser--children .content) ""))
          ((string= .type "hardBreak")
           "\n")
          ((string= .type "heading")
           (format "%s %s" (string-utils-string-repeat "*" .attrs.level) (adf-parser--children .content)))
          ((string= .type "inlineCard")
           (format "<%s>" .attrs.url))
          ((string= .type "listItem")
           (format "- %s" (string-join (adf-parser--children .content) "")))
          ((string= .type "media")
           (format "[[%s]]" .attrs.alt))
          ((string= .type "mediaGroup")
           "[media group]")
          ((string= .type "mediaSingle")
           (string-join (adf-parser--children .content) "\n"))
          ((string= .type "mention")
           .attr.text)
          ((string= .type "orderedList")
           (string-join (adf-parser--children .content) "\n"))
          ((string= .type "panel")
           (string-join (adf-parser--children .content) " "))
          ((string= .type "paragraph")
           (format "%s\n" (string-join (adf-parser--children .content) " ")))
          ((string= .type "rule")
           "\n-----\n")
          ((string= .type "status")
           (format "[%s]" .attrs.text))
          ((string= .type "table")
           (string-join (adf-parser--children .content) "\n"))
          ((string= .type "tableCell")
           (format "| %s " (string-join (adf-parser--children .content) "")))
          ((string= .type "tableHeader")
           (format "| %s " (string-join (adf-parser--children .content) "")))
          ((string= .type "tableRow")
           (string-join (adf-parser--children .content) ""))
          ((string= .type "text")
           (adf-parser--apply-many-marks .text .marks)))))

(provide 'adf-parser)
