(defun timeclock-summarise ()
  "Summarise timeclock and display the summary in a buffer."
  (interactive)
  (with-current-buffer (find-file-noselect timeclock-file)
    (save-excursion
      (goto-char (point-min))
      (let ((last-time nil))
        (while (not (eobp))
          (let* ((line (buffer-substring-no-properties (line-beginning-position) (line-end-position)))
                 (matches (s-match timeclock-moment-regexp line))
                 (io (string-to-char(nth 1 matches)))
                 (year (string-to-number (nth 2 matches)))
                 (month (string-to-number (nth 3 matches)))
                 (day (string-to-number (nth 4 matches)))
                 (hour (string-to-number (nth 5 matches)))
                 (minute (string-to-number (nth 6 matches)))
                 (secs (string-to-number (nth 7 matches)))
                 (note (nth 8 matches))
                 (encoded-time (encode-time (list secs minute hour day month year nil -1 nil))))
            (forward-line)))))))
