#!/bin/sh
echo "Install paru..."
if ! command -v paru &> /dev/null
then
    sudo pacman -S --needed base-devel
    git clone https://aur.archlinux.org/paru.git ~/.paru
    cd ~/.paru || return
    makepkg -si
else
    echo "  Already installed"
fi

printf "\n\nInstall my dev packages..."
paru -S --needed \
    aerc \
    alacritty \
    aspell \
    aspell-en \
    aspnet-runtime \
    aspnet-targeting-pack \
    autoconf \
    automake \
    aws-cli-v2-bin \
    aws-session-manager-plugin \
    base-devel \
    bash-completion \
    bash-language-server \
    bat \
    bitwarden-cli \
    bitwarden-rofi \
    calc \
    ccls \
    chezmoi \
    cmake \
    composer \
    devtools \
    direnv \
    discord \
    docker \
    docker-compose \
    dotnet-runtime \
    dotnet-sdk \
    dropbox \
    dtach \
    dunst \
    editorconfig-core-c \
    efibootmgr \
    elm-bin \
    elm-format-bin \
    elm-language-server \
    emacs-nativecomp \
    fd \
    firefox-developer-edition \
    fzf \
    ghcup-hs-bin \
    git \
    github-cli \
    glslang \
    gnome-keyring \
    gobuster-bin \
    go-jira \
    gotop-bin \
    gparted \
    graphviz \
    helix \
    heroku-cli-bin \
    hoogle \
    htop \
    hub \
    i3blocks \
    i3-gaps \
    i3lock \
    i3status \
    i3status-rust \
    insomnia-bin \
    isync \
    jdk-openjdk \
    jq \
    js-beautify \
    keynav \
    kitty \
    lazygit \
    librewolf-bin \
    make \
    man-db \
    mu \
    neovim \
    nerd-fonts-complete \
    netstandard-targeting-pack-bin \
    net-tools \
    networkmanager \
    nmap \
    npm \
    nvm \
    nyxt \
    omnisharp-roslyn \
    openvpn3 \
    p7zip \
    pacmanfile \
    paru-bin \
    pass \
    pass-import \
    pass-otp \
    pdfjs \
    pgformatter \
    php \
    php7 \
    php7-gd \
    php7-igbinary \
    php7-imagick \
    php7-imap \
    php7-intl \
    php7-memcache \
    php7-memcached \
    php7-pgsql \
    php7-phpdbg \
    php7-sodium \
    php7-sqlite \
    php-gd \
    php-imagick \
    php-imap \
    php-intl \
    php-sodium \
    picom \
    pkgconf \
    postman-bin \
    procs \
    psysh \
    pulseaudio-alsa \
    pyright \
    python-adblock \
    python-lsp-server \
    python-pip \
    qutebrowser \
    rcm \
    reflector \
    ripgrep \
    rofi \
    roswell \
    rsync \
    rust \
    scrot \
    sed \
    sfdx-cli \
    shellcheck \
    slack-desktop \
    spectrwm \
    spotify \
    starship \
    stylelint \
    task \
    taskwarrior-tui \
    terraform \
    texinfo \
    tidy \
    tor \
    unison \
    vim \
    visual-studio-code-bin \
    wget \
    which \
    wtfutil \
    xclip \
    xdg-utils \
    xdotool \
    yarn \
    zoom \
    zoxide
