vim.keymap.set('n', '<localleader>a', function()
  require('decisive').align_csv({})
end, { silent = true, desc = 'Align columns' })
vim.keymap.set('n', '<localleader>A', function()
  require('decisive').align_csv_clear({})
end, { silent = true, desc = 'Unalign columns' })
vim.keymap.set('n', '[c', function()
  require('decisive').align_csv_prev_col({})
end, { silent = true, desc = 'Previous column' })
vim.keymap.set('n', ']c', function()
  require('decisive').align_csv_next_col({})
end, { silent = true, desc = 'Next column' })
