hook global InsertCompletionShow .* %{
    try %{
        # this command temporarily removes cursors preceded by whitespace;
        # if there are no cursors left, it raises an error, does not
        # continue to execute the mapping commands, and the error is eaten
        # by the `try` command so no warning appears.
        execute-keys -draft 'h<a-K>\h<ret>'
        map window insert <tab> <c-n>
        map window insert <s-tab> <c-p>
    }
}
hook global InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
}
hook global WinCreate ^[^*]+$ %{editorconfig-load}

# Load the plugin manager
source "%val{config}/plugins/plug.kak/rc/plug.kak"

# LSP
eval %sh{kak-lsp --kakoune -s $kak_session}
hook global WinSetOption filetype=(php) %{
        lsp-enable-window
}

# Fuzzy finder
def find -params 1 -shell-script-candidates %{ find -type f } %{ edit %arg{1} }

# Settings
add-highlighter global number-lines
