theme = "jellybeans"

[editor]
line-number = "relative"
mouse = false
shell = ["bash", "-c"]
idle-timeout = 400
auto-format = true
undercurl = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "version-control"]

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_line_start"
"C-e" = "file_picker_in_current_buffer_directory"
"C-r" = ":reload-all"
"C-m" = "save_selection"

[keys.select]
"$" = "goto_line_end"
"C-m" = "save_selection"

[keys.insert]
"C-space" = "completion"

[keys.normal.space]
"." = "file_picker_in_current_buffer_directory"
"space" = "file_picker_in_current_directory"
"minus" = ":sh zellij run -ci -- yazi %{dirname}"

[keys.normal."C-f"]
"t" = ":pipe ascii-table"

[keys.normal.space.c]
r = "rename_symbol"
a = "code_action"

[keys.normal.space.o]
"minus" = ":sh zellij run -ci -- yazi %{dirname}"
T = ":sh zellij run -cf -- pter ~/Dropbox/todo.txt"

[keys.normal.space.g]
g = ":sh zellij run -ci -- lazygit"
l = ":sh zellij run -ci -- tig %{filename}"
d = "changed_file_picker"

[keys.normal.space.r]
u = ":sh rpush %{filename:rel}"
d = ":sh rpull %{filename:rel}"

[keys.normal.space.f]
f = "file_picker"
Y = ":sh wl-copy '%{filename:rel}'"
