theme = "saxon"

[editor]
line-number = "relative"
mouse = false
shell = ["bash", "-c"]
idle-timeout = 400

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true

[keys.normal]
"$" = "goto_line_end"

[keys.select]
"$" = "goto_line_end"

[keys.insert]
"C-space" = "completion"