theme = "jellybeans"

[editor]
line-number = "relative"
mouse = false
shell = ["bash", "-i", "-c"]
idle-timeout = 400
auto-format = true
undercurl = true
default-line-ending = "lf"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[editor.lsp]
display-messages = true
display-inlay-hints = false

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["diagnostics", "selections", "position", "version-control"]

[keys.normal]
"$" = "goto_line_end"
"^" = "goto_line_start"
"C-e" = "file_picker_in_current_buffer_directory"

[keys.select]
"$" = "goto_line_end"

[keys.insert]
"C-space" = "completion"

[keys.normal.space]
g = {s = ":sh git_sync"}
"." = "file_picker_in_current_buffer_directory"
