[language-server]
# omnisharp = { command = "dotnet", args = ["/home/saxonj/Documents/omnisharp/OmniSharp.dll", "--languageserver"] }
omnisharp = { command = "omnisharp", args = ["--languageserver"] }
csharpls = { command = "csharp-ls", args = ["-l", "error"] }
graphql-ls = { command = "graphql-lsp", args = ["server", "-m", "stream"]}
haskell-language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }

[language-server.typescript-language-server.config.preferences]
importModuleSpecifierPreference = "relative"

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]
auto-format = true

[[language]]
name = "php"
roots = ["composer.json"]
auto-format = false

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "prettier" }

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "prettier" }

[[language]]
name = "graphql"
language-servers = ["graphql-ls"]
formatter = { command = "prettier" }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "prettier" }

[[language]]
name = "xml"
file-types = ["xml", "mobileconfig", "plist", "xib", "storyboard", "svg", "xsd", "gml", "xaml", "gir", "component"]

[[langauge]]
name = "haskell"
language-servers = [ "haskell-language-server" ]
