[language-server]
omnisharp = { command = "omnisharp", args = ["-lsp"] }
csharpls = { command = "csharp-ls", args = ["-l", "error"] }
graphql-ls = { command = "graphql-lsp", args = ["server", "-m", "stream"]}

[language-server.typescript-language-server.config.preferences]
importModuleSpecifierPreference = "relative"

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]
auto-format = true

[[language]]
name = "php"
roots = ["composer.json"]
auto-format = true

[[language]]
name = "tsx"
auto-format = true

[[language]]
name = "typescript"
auto-format = true

[[language]]
name = "graphql"
language-servers = ["graphql-ls"]

[[language]]
name = "javascript"
auto-format = true

[[language]]
name = "xml"
file-types = ["xml", "mobileconfig", "plist", "xib", "storyboard", "svg", "xsd", "gml", "xaml", "gir", "component"]
