[[language]]
name = "c-sharp"
language-server = { command = "omnisharp", args = ["--languageserver", "RoslynExtensionsOptions:enableDecompilationSupport=true", "RoslynExtensionsOptions:enableImportCompletion=true", "RoslynExtensionsOptions:enableAnalyzersSupport=true"] }

[[language]]
name = "php"
roots = ["composer.json"]