[[language]]
name = "php"
scope = "source.php"
injection-regex = "php"
file-types = ["php"]
shebangs = ["php"]
roots = ["composer.json", "index.php"]
language-server = { command = "intelephense", args = ["--stdio"] }
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[grammar]]
name = "php"
source = { git = "https://github.com/tree-sitter/tree-sitter-php"  }

[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py"]
shebangs = ["python"]
roots = []
comment-token = "#"
language-server = { command = "pylsp"}
indent = { tab-width = 4, unit = "    " }
auto-format = true

[[grammar]]
name = "python"
source = { git = "https://github.com/tree-sitter/tree-sitter-python"}

[[language]]
name = "graphql"
scope = "source.graphql"
injection-regex = "graphql"
file-types = ["gql", "graphql"]
roots = []
indent = { tab-width = 2, unit = "  " }
auto-format = true

[[grammar]]
name = "graphql"
source = { git = "https://github.com/bkegley/tree-sitter-graphql"  }

[[language]]
name = "elm"
scope = "source.elm"
injection-regex = "elm"
file-types = ["elm"]
roots = ["elm.json"]
auto-format = true
comment-token = "--"
language-server = { command = "elm-language-server" }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "elm"
source = { git = "https://github.com/elm-tooling/tree-sitter-elm"  }

[[language]]
name = "c-sharp"
scope = "source.csharp"
injection-regex = "c-?sharp"
file-types = ["cs"]
roots = ["sln", "csproj"]
comment-token = "//"
indent = { tab-width = 4, unit = "    " }
language-server = { command = "omnisharp", args = [ "--languageserver", "--stdio" ] }

[[grammar]]
name = "c-sharp"
source = { git = "https://github.com/tree-sitter/tree-sitter-c-sharp"  }
