[language-server]
omnisharp = { command = "omnisharp", args = ["--languageserver"] }
csharpls = { command = "csharp-ls", args = ["-l", "error"] }
graphql-ls = { command = "graphql-lsp", args = ["server", "-m", "stream"]}
haskell-language-server = { command = "haskell-language-server-wrapper", args = ["--lsp"] }
deno = { command = "deno", args = ["lsp"], config = {deno = {enable = true, lint = true}}, required-root-patterns = ["deno.jsonc", "deno.json"]}

[language-server.typescript-language-server]
required-root-patterns = ["package.json"]

[language-server.typescript-language-server.config.preferences]
importModuleSpecifierPreference = "relative"

[[language]]
name = "c-sharp"
language-servers = ["omnisharp"]
auto-format = true
formatter = { command = "helix-zellij", args = ["waka"] }

[[language]]
name = "php"
roots = ["composer.json"]
auto-format = true
formatter = { command = "helix-zellij", args = ["waka"] }

[[language]]
name = "tsx"
auto-format = true
formatter = { command = "helix-zellij", args = ["waka", "prettier"] }
language-servers = ["typescript-language-server", "deno"]

[[language]]
name = "typescript"
auto-format = true
formatter = { command = "helix-zellij", args = ["waka", "prettier"] }
language-servers = ["typescript-language-server", "deno"]
roots = ["deno.json", "deno.jsonc", "package.json"]

[[language]]
name = "graphql"
language-servers = ["graphql-ls"]
formatter = { command = "helix-zellij", args = ["waka", "prettier"] }

[[language]]
name = "javascript"
auto-format = true
formatter = { command = "helix-zellij", args = ["waka", "prettier"] }

[[language]]
name = "xml"
file-types = ["xml", "mobileconfig", "plist", "xib", "storyboard", "svg", "xsd", "gml", "xaml", "gir", "component"]
auto-format = true
formatter = { command = "helix-zellij", args = ["waka"] }

[[langauge]]
name = "haskell"
language-servers = [ "haskell-language-server" ]
auto-format = true
formatter = { command = "helix-zellij", args = ["waka", "ormolu"] }
