[[language]]
name = "c-sharp"
language-server = { command = "omnisharp", args = ["--languageserver"] }
auto-format = true

[[language]]
name = "php"
roots = ["composer.json"]
auto-format = true

[[language]]
name = "tsx"
auto-format = true
config = {preferences.importModuleSpecifierPreference = "relative"}

[[language]]
name = "typescript"
config = {preferences.importModuleSpecifierPreference = "relative"}
auto-format = true

[[language]]
name = "graphql"
language-server = { command = "graphql-lsp", args = ["server", "-m", "stream"]}