colorscheme ef-winter

# Windowing
require-module kitty

# general
set global indentwidth 2
set global ui_options terminal_assistant=none
set global tabstop 2
set global indentwidth 2

# general highlighters
add-highlighter global/git-diff flag-lines Default git_diff_flags
add-highlighter global/number-lines number-lines -hlcursor -relative
add-highlighter global/hl-col-120 column 120 default,black+d

# better grep
set-option global grepcmd 'rg --column --smart-case --sort path'

declare-user-mode window
map global window n ':kitty-terminal-window kak -c %val{session}<ret>' -docstring 'New Client'
map global normal <c-w> ':enter-user-mode window<ret>' -docstring 'Windows'
