colorscheme ef-winter

# Windowing
require-module zellij

# general
set global indentwidth 2
set global ui_options terminal_assistant=none
set global tabstop 2
set global indentwidth 2

# general highlighters
add-highlighter global/git-diff flag-lines Default git_diff_flags
add-highlighter global/number-lines number-lines -hlcursor -relative
add-highlighter global/hl-col-120 column 120 default,black+d

# better grep
set-option global grepcmd 'rg --column --smart-case --sort path'

# Global binds
map global normal <c-c> ':comment-line' -docstring 'Comment'

declare-user-mode open

declare-user-mode window
map global window v ':zellij-terminal-horizontal kak -c %val{session}<ret>' -docstring 'Vertical Split'
map global window s ':zellij-terminal-vertical kak -c %val{session}<ret>' -docstring 'Horizontal Split'
map global normal <c-w> ':enter-user-mode window<ret>' -docstring 'Windows'

define-command -params 1 -docstring %{Run a project command} project-run %{
  evaluate-commands %sh{
    echo "zellij-terminal-horizontal kak -c $kak_session"
		file="$(mktemp)"
		echo "edit! -fifo $file"
		$1 > $file & disown
  }
}

complete-command -menu project-run shell-script-candidates kak_runner_options
