colorscheme ef-winter

# Windowing
require-module zellij

# general
set global indentwidth 2
set global ui_options terminal_assistant=none
set global tabstop 2
set global indentwidth 2

# general highlighters
add-highlighter global/git-diff flag-lines Default git_diff_flags
add-highlighter global/number-lines number-lines -hlcursor -relative
add-highlighter global/hl-col-120 column 120 default,black+d

# better grep
set-option global grepcmd 'rg --column --smart-case --sort path'

declare-user-mode window
map global window h ':zellij-action move-focus left<ret>' -docstring 'Focus left'
map global window l ':zellij-action move-focus right<ret>' -docstring 'Focus right'
map global window j ':zellij-action move-focus down<ret>' -docstring 'Focus down'
map global window k ':zellij-action move-focus up<ret>' -docstring 'Focus up'

map global window v ':zellij-terminal-horizontal kak -c %val{session}<ret>' -docstring 'Verical split'
map global window s ':zellij-terminal-vertical kak -c %val{session}<ret>' -docstring 'Horizontal split'
map global window x ':zellij-action close-pane<ret>' -docstring 'Close'

map global normal <c-w> ':enter-user-mode window<ret>' -docstring 'Windows'
