# c-sharp
[language.c-sharp.grammar.source.git]
url = "https://github.com/tree-sitter/tree-sitter-c-sharp"
pin = "5b60f99545fea00a33bbfae5be956f684c4c69e2"

[language.c-sharp.grammar]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "c-sharp.so"]
link_flags = ["-O3"]

[language.c-sharp.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "master"

[language.c-sharp.queries]
path = "runtime/queries/c-sharp"

