[language.c-sharp.grammar.source.git]
url = "https://github.com/tree-sitter/tree-sitter-c-sharp"
pin = "92c0a9431400cd8b6b6ee7503f81da3ae83fc830"

[language.c-sharp.grammar]
path = "src"
compile = "cc"
compile_args = ["-c", "-fpic", "../scanner.c", "../parser.c", "-I", ".."]
compile_flags = ["-O3"]
link = "cc"
link_args = ["-shared", "-fpic", "scanner.o", "parser.o", "-o", "c-sharp.so"]
link_flags = ["-O3"]

[language.c-sharp.queries.source.git]
url = "https://github.com/helix-editor/helix"
pin = "be307a420480178c1bc443992c8336f6471b8b7b"

[language.c-sharp.queries]
path = "runtime/queries/c-sharp"

